Use Application.compile_env! instead of no-bang version
We use Application.compile_env! to set `@endpoint` module attribute so
error is a little clearer (and "closer" to the error site).

This is the new error:

```
== Compilation error in file lib/phoenix_test/live.ex ==
** (ArgumentError) could not fetch application environment :endpoint for application :phoenix_test because the application was not loaded nor configured
```

Previously, it would show something like this:

```
== Compilation error in file lib/phoenix_test/live.ex ==
** (RuntimeError) module attribute @endpoint not set for socket/2
```