Fix: Raise error if implicit + explicit label found (#142)
Given

```
<label for="greeting">Hello</label>
<input id="greeting" />

<label>Hello <input id="second_greeting" /></label>

session
|> fill_in("Hello", with: "world")
```

Expected

```
ArgumentError: Found many elements with label "Hello" and matching the provided selectors
```

Actual

No error. Label with explicit for wins, other one ignored.

This behavior is stricter than the HTML spec (the element with `id` would win out), 
but it seems good that we can provide feedback to our users earlier since this is 
likely undesired behavior.